### ISSUE TITLE
Compilazione per BananaPi R1 (Lamobo R1)

### ISSUE THREAD

**Issue by mikysal78** [ninuxorg/openwrt-basilicata#7]
Compilando da sorgente va a buon fine e questo è il [.config](https://pastebin.com/tJYgp9hj)
Come possiamo integrarlo su ansible-nnxx?

Grazie.

**Comment by nemesifier** [comment]
Dallo screenshot che hai inviato su telegram sembra che in questo caso manchi il subtarget.

Per supportare questa cosa bisogna cambiare un pò di file sul ruolo ansible:

- [templates/compile/compile.sh.jinja2](https://github.com/openwisp/ansible-openwisp2-imagegenerator/blob/master/templates/compile/compile.sh.jinja2#L24-L26)
- [templates/generator/find.sh.jinja2](https://github.com/openwisp/ansible-openwisp2-imagegenerator/blob/master/templates/generator/find.sh.jinja2)
- [templates/build/build-images.sh.jinja2](https://github.com/openwisp/ansible-openwisp2-imagegenerator/blob/master/templates/build/build-images.sh.jinja2#L11)
- [tasks/3-generator.yml](https://github.com/openwisp/ansible-openwisp2-imagegenerator/blob/master/tasks/3-generator.yml)
