### ISSUE TITLE
'dict object' has no attribute 'luci_openwisp'

### ISSUE THREAD

**Issue by mikysal78** [ninuxorg/openwrt-basilicata#8]
la role di ansible-openwisp2-imagegenerator ha un bug ed ansible-nnxx non funziona più!
L'errore è riportato in https://pastebin.com/aGBGM9GQ

**Comment by nemesifier** [comment]
Fixato su ruolo ansible-openwisp2-imagenerator
https://github.com/openwisp/ansible-openwisp2-imagegenerator/issues/10
